# Multivariate Analysis
Study more than two variables together.

In [1]:
import pandas as pd
import matplotlib.pyplot as plt

df = pd.read_csv("chai_sales.csv").drop_duplicates()

## Correlation matrix

In [2]:
numeric_cols = [
    "order_hour", "quantity", "unit_price", "discount_percent",
    "total_amount", "temperature_c", "customer_rating", "prep_time_min"
]

corr = df[numeric_cols].corr()
corr

,order_hour,quantity,unit_price,discount_percent,total_amount,temperature_c,customer_rating,prep_time_min
order_hour,1.000000,0.109455,0.075655,0.027551,0.130158,0.031859,0.045884,-0.028176
quantity,0.109455,1.000000,0.037007,-0.077412,0.809735,-0.020920,0.068094,0.210055
unit_price,0.075655,0.037007,1.000000,0.002987,0.405458,-0.059240,-0.089210,0.004661
discount_percent,0.027551,-0.077412,0.002987,1.000000,-0.151123,-0.004102,-0.056415,-0.026100
total_amount,0.130158,0.809735,0.405458,-0.151123,1.000000,-0.042761,0.039390,0.183595
temperature_c,0.031859,-0.020920,-0.059240,-0.004102,-0.042761,1.000000,0.005735,0.066832
customer_rating,0.045884,0.068094,-0.089210,-0.056415,0.039390,0.005735,1.000000,-0.014099
prep_time_min,-0.028176,0.210055,0.004661,-0.026100,0.183595,0.066832,-0.014099,1.000000

In [ ]:
fig, ax = plt.subplots(figsize=(9, 6))
img = ax.imshow(corr.values)
ax.set_xticks(range(len(corr.columns)))
ax.set_yticks(range(len(corr.columns)))
ax.set_xticklabels(corr.columns, rotation=45, ha="right")
ax.set_yticklabels(corr.columns)
fig.colorbar(img)
plt.title("Correlation Matrix")
plt.tight_layout()
plt.show()

## City + chai type + sales

In [ ]:
city_chai_sales = df.pivot_table(
    values="total_amount",
    index="city",
    columns="chai_type",
    aggfunc="mean"
)
city_chai_sales

## Weather + customer type + amount

In [3]:
df.groupby(["weather", "customer_type"])["total_amount"].mean().unstack()

customer_type      Local  Office Worker      Other     Student    Tourist
weather
Cloudy         78.666667      50.862500  78.758621   83.473214  66.887500
Cold           83.991667      64.875000  77.913462  101.700000  70.666667
Hot            62.685185      82.660714  71.070000   66.557692  74.177419
Rainy          71.360294      82.225000  77.965909   83.891667  75.656250
Sunny          77.944444      81.489130  66.040000   94.552632  83.391667